# Generated by Django 4.2.6 on 2023-12-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_like_unique_like_like_unique_like_moment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
            ],
        ),
        migrations.CreateModel(
            name='LikeMoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='moment',
            name='title',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='likemoment',
            name='moment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moment'),
        ),
        migrations.AddConstraint(
            model_name='likemoment',
            constraint=models.UniqueConstraint(fields=('author', 'moment'), name='unique_like_moment'),
        ),
        migrations.AddConstraint(
            model_name='likecomment',
            constraint=models.UniqueConstraint(fields=('author', 'comment'), name='unique_like_comment'),
        ),
    ]
